application: quotos-1322
version: 1
runtime: go
api_version: go1


handlers:
- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /quotes
  static_dir: static/json
  mime_type: application/json

- url: /.*
  script: _go_app
